version: '3'
services:
  # Application
  api-boilerplate:
    image: api-boilerplate:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on: []
    environment:
      NAME: api-boilerplate
      PORT: '3000'
      LOG_LEVEL: info
    volumes:
      - ./src:/app/src # For nodemon to watch for file changes
    ports:
      - '3000:3000' # Application port
      - '9229:9229' # Debug port
